### PR TITLE
Bug: Completing an order

### LINKED ISSUE #4: Bug: Completing an order doesn't work
When the user clicks **Complete Order** from the cart view, and then selects a payment type, and then clicks on the **Complete Order** button on that dialog, the order does not complete. It is expected for the order to be marked as complete so that it shows up in the **My Orders** view and the cart is emptied.

### PR DESCRIPTION
**Pull request by evymai**
Resolves #4 
When the user clicks Complete Order from the cart view, and then selects a payment type, and then clicks on the Complete Order button on that dialog, the order is marked as complete so that it shows up in the My Orders view and the cart is emptied.

##Changes

- data/orders.js
   - line 20: remove /complete
   - line 26: paymentTypeId as argument 
- data/payment-types.js
   - line 12/23: remove - from payment-types
- pages/cart.js
   - formatting
   - line 36: adding payment object for JSON
- pages/my-orders.js
   - formatting
   - line 15-46: adding fetch calls and functionality to calculate total and 
     retrieve payment type
   - line 57/59: change property names

##Testing

- [x] make sure API debugger is running
- [x] login to Bangazon
- [x] navigate to cart
- [x] click complete order and add a payment type
- [x] page should navigate to My Orders
- [x] order should show up in My Orders with the total cost and payment
- [x] navigate back to cart and make sure cart was emptied

### CODE REVIEW

File: pages/my-orders.js [hunk 1]
```diff
@@ -1,18 +1,49 @@
...
+        const fetchPaymentTypes = ordersData.map(async (order) => {
+          try {
+            const paymentTypeRes = await fetch(order.payment_type)
+            if (!paymentTypeRes.ok) {
+              throw new Error(`Failed to fetch payment type for order ${order.id}`)
+            }
+            const paymentTypeData = await paymentTypeRes.json()
+            return { ...order, payment_type: paymentTypeData }
+          } catch (error) {
+            console.error(error)
```
Comment (HewsonSchulz) [inline pages/my-orders.js:25]: One here.

File: pages/my-orders.js [hunk 2]
```diff
@@ -1,18 +1,49 @@
...
+              for (const lineItem of order.lineitems) {
+                total += lineItem.product.price;
+              }
+            }
+            return {
+              ...order,
+              total: total.toFixed(2),
+            };
+          });
+          console.log(ordersDataTotal)
```
Comment (HewsonSchulz) [inline pages/my-orders.js:44]: And one here.

**Review by HewsonSchulz — CHANGES_REQUESTED** [review]
All looks good, just a couple `console.log`s that should be removed.

**Review by HewsonSchulz — APPROVED** [review]
All looks good!
